# # .gitlab-ci.yml
# stages:
#   - build
#   - deploy

# variables:
#   DOCKER_IMAGE: registry.gitlab.com/i_never_bot/i_never_bot

# build:
#   stage: build
#   script:
#     - docker build -t $DOCKER_IMAGE .
#     - docker push $DOCKER_IMAGE
#   only:
#     - main

# deploy:
#   stage: deploy
#   script:
#     - docker-compose down
#     - docker-compose pull
#     - docker-compose up -d
#   only:
#     - main

stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    docker build -t i_never_bot .

deploy-job:
  stage: deploy
  script:
    docker-compose up -d