# .gitlab-ci.yml
stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: registry.gitlab.com/your_project/telegram_bot

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  only:
    - main

deploy:
  stage: deploy
  script:
    - docker-compose down
    - docker-compose pull
    - docker-compose up -d
  only:
    - main
