version: '3.8'

services:
  i_never_bot:
    build:
      context: .
    environment:
      - Token_tg=${Token_tg}
      - Token_MDB=${Token_MDB}
      - Your_user_ID=${Your_user_ID}
    volumes:
      - ./logs:/app/logs
    restart: always
